apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: s3-bucket
spec:
  organization: f5xc-tenant-ops
  token:
    secretKeyRef:
      name: terraformrc
      key: token
  destroyOnDeletion: true
  module:
    source: "terraform-aws-modules/s3-bucket/aws"
    version: "4.2.2"
  outputs:
    - name: bucket_id
    - name: bucket_arn
  variables:
    - name: bucket
      value: "f5xc-tenant-ops-certificates-dev"
    - name: acl
      value: "private"
    - name: region
      value: "us-west-2"
  workspace:
    name: tops-infra-dev