apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform-cloud
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: 
      prune: true
    syncOptions:
      - ServerSideApply=true
  destination:
    name: in-cluster
    namespace: tfc-operator-system
  sources:
    - chart: terraform
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 1.1.2
      helm:
        valueFiles:
        - $values/tfc-operator/values.yml
    - repoURL: https://github.com/f5xc-TenantOps/f5xc-tops-mgmt-cluster.git
      targetRevision: HEAD
      path: tfc-operator
      ref: values
