---
apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: tops-infra-dev
spec:
  organization: f5xc-tenant-ops
  terraformVersion: 1.6.2
  token:
    secretKeyRef:
      name: terraformrc
      key: token
  name: tops-infra-dev
  description: F5XC Tenant Ops Infrastructure - Development
  applyMethod: auto
  terraformVariables:
    - name: environment
      value: dev
      hcl: false
      sensitive: false
  environmentVariables:
    - name: AWS_SECRET_ACCESS_KEY
      sensitive: true
      hcl: false
      valueFrom:
        secretKeyRef:
          name: workspacesecrets
          key: AWS_SECRET_ACCESS_KEY
    - name: AWS_ACCESS_KEY_ID
      sensitive: true
      hcl: false
      valueFrom:
        secretKeyRef:
          name: workspacesecrets
          key: AWS_ACCESS_KEY_ID
    - name: mcn_lab_token
      sensitive: true
      hcl: false
      valueFrom:
        secretKeyRef:
          name: tenant-tokens
          key: mcn_lab_token
  versionControl:
    repository: f5xc-TenantOps/f5xc-tops-infra
    branch: dev
    oAuthTokenID: ot-mshXc8tPKM35f6Ve

